const data = [
  {
    id: 1,
    fullName: "Jaynell",
    avatar: "https://robohash.org/veniamnisiut.png?size=50x50&set=set1",
    university: "Belarussian State Academy of Music",
    department: "Engineering",
  },
  {
    id: 2,
    fullName: "Emalia",
    avatar: "https://robohash.org/aperiamquiest.png?size=50x50&set=set1",
    university: "Planwel University",
    department: "Services",
  },
  {
    id: 3,
    fullName: "Colin",
    avatar: "https://robohash.org/eosimpeditet.png?size=50x50&set=set1",
    university: "Castleton State College",
    department: "Marketing",
  },
  {
    id: 4,
    fullName: "Caresse",
    avatar: "https://robohash.org/quiavelplaceat.png?size=50x50&set=set1",
    university: "University of Applied Sciences Basel (FHBB )",
    department: "Sales",
  },
  {
    id: 5,
    fullName: "Evelyn",
    avatar: "https://robohash.org/doloresestmodi.png?size=50x50&set=set1",
    university: "Technical University of Denmark",
    department: "Product Management",
  },
  {
    id: 6,
    fullName: "Jorge",
    avatar:
      "https://robohash.org/necessitatibusaliquamoccaecati.png?size=50x50&set=set1",
    university: "European Graduate School, Media & Communications",
    department: "Human Resources",
  },
  {
    id: 7,
    fullName: "Sher",
    avatar:
      "https://robohash.org/dignissimossuntvoluptatem.png?size=50x50&set=set1",
    university: "Divine Word College of Legazpi",
    department: "Human Resources",
  },
  {
    id: 8,
    fullName: "Therine",
    avatar: "https://robohash.org/quorepellatunde.png?size=50x50&set=set1",
    university:
      "Central America Health Sciences University (Belize Medical College)",
    department: "Services",
  },
  {
    id: 9,
    fullName: "Darelle",
    avatar:
      "https://robohash.org/corporisitaquelaudantium.png?size=50x50&set=set1",
    university: "Universidad Nacional de Entre Ríos",
    department: "Product Management",
  },
  {
    id: 10,
    fullName: "Balduin",
    avatar: "https://robohash.org/accusantiumutautem.png?size=50x50&set=set1",
    university: "Wright State University",
    department: "Engineering",
  },
  {
    id: 11,
    fullName: "Edy",
    avatar:
      "https://robohash.org/doloribusvoluptasnatus.png?size=50x50&set=set1",
    university: "Riara University School of Business and Law",
    department: "Training",
  },
  {
    id: 12,
    fullName: "Rosemaria",
    avatar:
      "https://robohash.org/excepturinecessitatibuslaborum.png?size=50x50&set=set1",
    university: "Odessa National Marine University",
    department: "Legal",
  },
  {
    id: 13,
    fullName: "Shanda",
    avatar: "https://robohash.org/estautcommodi.png?size=50x50&set=set1",
    university: "Universidad Nacional de Jujuy",
    department: "Accounting",
  },
  {
    id: 14,
    fullName: "Cacilia",
    avatar: "https://robohash.org/voluptasnamsuscipit.png?size=50x50&set=set1",
    university: "East Delta University",
    department: "Research and Development",
  },
  {
    id: 15,
    fullName: "Gennifer",
    avatar: "https://robohash.org/exminimaautem.png?size=50x50&set=set1",
    university: "Bowen University",
    department: "Research and Development",
  },
  {
    id: 16,
    fullName: "Rowe",
    avatar: "https://robohash.org/rerumassumendamagnam.png?size=50x50&set=set1",
    university: "University of Batangas",
    department: "Legal",
  },
  {
    id: 17,
    fullName: "Rudd",
    avatar: "https://robohash.org/modiculpabeatae.png?size=50x50&set=set1",
    university: "Darul Takzim Institute of Technology",
    department: "Engineering",
  },
  {
    id: 18,
    fullName: "Fanny",
    avatar:
      "https://robohash.org/perspiciatisvoluptatumest.png?size=50x50&set=set1",
    university: "University of Liberia",
    department: "Services",
  },
  {
    id: 19,
    fullName: "Helenka",
    avatar:
      "https://robohash.org/cupiditateautvoluptatem.png?size=50x50&set=set1",
    university: "Warren Wilson College",
    department: "Engineering",
  },
  {
    id: 20,
    fullName: "Derby",
    avatar: "https://robohash.org/fugaestest.png?size=50x50&set=set1",
    university: "Martin Luther College",
    department: "Services",
  },
  {
    id: 21,
    fullName: "Sebastian",
    avatar: "https://robohash.org/illumfugadolorem.png?size=50x50&set=set1",
    university: "Shanghai Television University",
    department: "Research and Development",
  },
  {
    id: 22,
    fullName: "Ileana",
    avatar: "https://robohash.org/quidemaliquamquos.png?size=50x50&set=set1",
    university: "Shizuoka University",
    department: "Engineering",
  },
  {
    id: 23,
    fullName: "Corabelle",
    avatar:
      "https://robohash.org/temporelaboriosamarchitecto.png?size=50x50&set=set1",
    university: "Iwate Medical University",
    department: "Accounting",
  },
  {
    id: 24,
    fullName: "Sophia",
    avatar: "https://robohash.org/eaerrorest.png?size=50x50&set=set1",
    university: "Universidad del Museo Social Argentino",
    department: "Services",
  },
  {
    id: 25,
    fullName: "Cirillo",
    avatar: "https://robohash.org/quisveniamqui.png?size=50x50&set=set1",
    university: "Maria Grzegorzewska College for Special Education",
    department: "Research and Development",
  },
  {
    id: 26,
    fullName: "Benedicta",
    avatar:
      "https://robohash.org/essevoluptatemdolorum.png?size=50x50&set=set1",
    university: "Universidade Federal do Maranhão",
    department: "Marketing",
  },
  {
    id: 27,
    fullName: "Ab",
    avatar: "https://robohash.org/aperiamenimfacilis.png?size=50x50&set=set1",
    university: "Ohtani Women's University",
    department: "Legal",
  },
  {
    id: 28,
    fullName: "Ardisj",
    avatar: "https://robohash.org/hicquastempora.png?size=50x50&set=set1",
    university: "Detroit College of Business",
    department: "Marketing",
  },
  {
    id: 29,
    fullName: "Rodd",
    avatar: "https://robohash.org/sedametmaiores.png?size=50x50&set=set1",
    university: "De Haagse Hogeschool",
    department: "Support",
  },
  {
    id: 30,
    fullName: "Darice",
    avatar: "https://robohash.org/reiciendisetet.png?size=50x50&set=set1",
    university: "University of Santo Tomas",
    department: "Product Management",
  },
  {
    id: 31,
    fullName: "Noami",
    avatar: "https://robohash.org/deseruntmollitiaet.png?size=50x50&set=set1",
    university: "Hatyai University",
    department: "Support",
  },
  {
    id: 32,
    fullName: "Clarette",
    avatar: "https://robohash.org/voluptatemnihilanimi.png?size=50x50&set=set1",
    university: "Neumann College",
    department: "Marketing",
  },
  {
    id: 33,
    fullName: "Worth",
    avatar:
      "https://robohash.org/assumendaetvoluptates.png?size=50x50&set=set1",
    university: "Ontario College of Art and Design",
    department: "Legal",
  },
  {
    id: 34,
    fullName: "Verene",
    avatar:
      "https://robohash.org/mollitiadolorummaxime.png?size=50x50&set=set1",
    university: "Universidad Nacional de la Amazonía Peruana",
    department: "Support",
  },
  {
    id: 35,
    fullName: "Abby",
    avatar:
      "https://robohash.org/aspernaturassumendacorporis.png?size=50x50&set=set1",
    university: "Technological University (Myeik)",
    department: "Services",
  },
  {
    id: 36,
    fullName: "Steffie",
    avatar:
      "https://robohash.org/dolorummaximeassumenda.png?size=50x50&set=set1",
    university: "Universidade da Amazônia",
    department: "Services",
  },
  {
    id: 37,
    fullName: "Hammad",
    avatar:
      "https://robohash.org/nulladoloremqueassumenda.png?size=50x50&set=set1",
    university: "University of Pittsburgh at Greensburg",
    department: "Human Resources",
  },
  {
    id: 38,
    fullName: "Loella",
    avatar: "https://robohash.org/autemvoluptatibusat.png?size=50x50&set=set1",
    university: "Philosophisch-Theologische Hochschule Sankt Georgen",
    department: "Product Management",
  },
  {
    id: 39,
    fullName: "Seymour",
    avatar: "https://robohash.org/natusquoomnis.png?size=50x50&set=set1",
    university: "Beder University",
    department: "Accounting",
  },
  {
    id: 40,
    fullName: "Martyn",
    avatar:
      "https://robohash.org/errordelenitiincidunt.png?size=50x50&set=set1",
    university: "Toyama University",
    department: "Human Resources",
  },
  {
    id: 41,
    fullName: "Sutherland",
    avatar:
      "https://robohash.org/inventoresitdignissimos.png?size=50x50&set=set1",
    university: "Miryang National University",
    department: "Product Management",
  },
  {
    id: 42,
    fullName: "Mabelle",
    avatar: "https://robohash.org/praesentiumquasiamet.png?size=50x50&set=set1",
    university: "Roskilde University",
    department: "Product Management",
  },
  {
    id: 43,
    fullName: "Merridie",
    avatar: "https://robohash.org/consequaturrerumet.png?size=50x50&set=set1",
    university: "Huston-Tillotson College",
    department: "Product Management",
  },
  {
    id: 44,
    fullName: "Dolph",
    avatar: "https://robohash.org/utrerumconsectetur.png?size=50x50&set=set1",
    university: "Awadhesh Pratap Singh University",
    department: "Sales",
  },
  {
    id: 45,
    fullName: "Maximilian",
    avatar: "https://robohash.org/inventorevoluptasin.png?size=50x50&set=set1",
    university: "Massachusetts School of Professional Psychology",
    department: "Research and Development",
  },
  {
    id: 46,
    fullName: "Cory",
    avatar: "https://robohash.org/excepturietexplicabo.png?size=50x50&set=set1",
    university: "Universidad La Republica",
    department: "Business Development",
  },
  {
    id: 47,
    fullName: "Berenice",
    avatar: "https://robohash.org/nonexdolore.png?size=50x50&set=set1",
    university: "Adrian College",
    department: "Support",
  },
  {
    id: 48,
    fullName: "Shandra",
    avatar:
      "https://robohash.org/delenitienimmolestiae.png?size=50x50&set=set1",
    university: "Dhaka University of Engineering and Technology",
    department: "Research and Development",
  },
  {
    id: 49,
    fullName: "Dwight",
    avatar: "https://robohash.org/voluptatessedet.png?size=50x50&set=set1",
    university: "Al-Islah University",
    department: "Human Resources",
  },
  {
    id: 50,
    fullName: "Katuscha",
    avatar: "https://robohash.org/rerumnonet.png?size=50x50&set=set1",
    university: "Nova Southeastern University",
    department: "Services",
  },
  {
    id: 51,
    fullName: "Ruthanne",
    avatar: "https://robohash.org/verofugaquaerat.png?size=50x50&set=set1",
    university: "Georgia College & State University",
    department: "Sales",
  },
  {
    id: 52,
    fullName: "Adham",
    avatar: "https://robohash.org/porroquiaoccaecati.png?size=50x50&set=set1",
    university: "Damascus University",
    department: "Engineering",
  },
  {
    id: 53,
    fullName: "Darby",
    avatar: "https://robohash.org/sedrerumsint.png?size=50x50&set=set1",
    university: "University of Colorado at Boulder",
    department: "Accounting",
  },
  {
    id: 54,
    fullName: "Gina",
    avatar:
      "https://robohash.org/consequaturrecusandaeet.png?size=50x50&set=set1",
    university: "Chongqing University of Post and Telecommunications",
    department: "Business Development",
  },
  {
    id: 55,
    fullName: "Samara",
    avatar: "https://robohash.org/etfugitvel.png?size=50x50&set=set1",
    university: "Capilano College",
    department: "Training",
  },
  {
    id: 56,
    fullName: "Gunar",
    avatar:
      "https://robohash.org/voluptatumexcepturiin.png?size=50x50&set=set1",
    university: "Universidade Federal de Lavras",
    department: "Product Management",
  },
  {
    id: 57,
    fullName: "Cristionna",
    avatar: "https://robohash.org/repellatutaut.png?size=50x50&set=set1",
    university: "University of the City of Manila",
    department: "Marketing",
  },
  {
    id: 58,
    fullName: "Rora",
    avatar: "https://robohash.org/voluptateillumqui.png?size=50x50&set=set1",
    university: "Osaka Electro-Communication University",
    department: "Legal",
  },
  {
    id: 59,
    fullName: "Sibylle",
    avatar:
      "https://robohash.org/consequunturverosuscipit.png?size=50x50&set=set1",
    university: "American Business & Technology University",
    department: "Training",
  },
  {
    id: 60,
    fullName: "Alfonso",
    avatar:
      "https://robohash.org/facerelaboriosamoccaecati.png?size=50x50&set=set1",
    university: "St. Francis Xavier University",
    department: "Marketing",
  },
  {
    id: 61,
    fullName: "Shanta",
    avatar: "https://robohash.org/estautdolores.png?size=50x50&set=set1",
    university: "Institute of Teachers Education, Tengku Ampuan Afzan",
    department: "Training",
  },
  {
    id: 62,
    fullName: "Irwinn",
    avatar: "https://robohash.org/maioresetvoluptatem.png?size=50x50&set=set1",
    university: "University of Washington, Tacoma",
    department: "Business Development",
  },
  {
    id: 63,
    fullName: "Dar",
    avatar:
      "https://robohash.org/architectovoluptatumexpedita.png?size=50x50&set=set1",
    university: "North South University",
    department: "Training",
  },
  {
    id: 64,
    fullName: "Melinda",
    avatar: "https://robohash.org/etfacilisvel.png?size=50x50&set=set1",
    university: "Mindanao State University - Iligan Institute of Technology",
    department: "Product Management",
  },
  {
    id: 65,
    fullName: "Valli",
    avatar: "https://robohash.org/dictaplaceatsunt.png?size=50x50&set=set1",
    university: "Macon State College",
    department: "Sales",
  },
  {
    id: 66,
    fullName: "Daniele",
    avatar: "https://robohash.org/quisquamsimiliqueest.png?size=50x50&set=set1",
    university: "Pan Africa Christian University",
    department: "Training",
  },
  {
    id: 67,
    fullName: "Bernardo",
    avatar: "https://robohash.org/eaeumsed.png?size=50x50&set=set1",
    university: "Universidad de Cartago Florencio del Castillo",
    department: "Product Management",
  },
  {
    id: 68,
    fullName: "Cacilia",
    avatar:
      "https://robohash.org/perferendisnecessitatibusmagni.png?size=50x50&set=set1",
    university: "Keck Graduate Institute of Applied Life Sciences",
    department: "Marketing",
  },
  {
    id: 69,
    fullName: "Sidonnie",
    avatar: "https://robohash.org/veritatislaborumqui.png?size=50x50&set=set1",
    university: "Tennessee Temple University",
    department: "Research and Development",
  },
  {
    id: 70,
    fullName: "June",
    avatar:
      "https://robohash.org/delectusquisrecusandae.png?size=50x50&set=set1",
    university: "Yeditepe University",
    department: "Engineering",
  },
  {
    id: 71,
    fullName: "Estell",
    avatar: "https://robohash.org/sedatqueet.png?size=50x50&set=set1",
    university: "Escuela Colombiana de Carreras Industriales",
    department: "Services",
  },
  {
    id: 72,
    fullName: "Daphene",
    avatar: "https://robohash.org/suntsuntvoluptatem.png?size=50x50&set=set1",
    university: "Middlesex University",
    department: "Human Resources",
  },
  {
    id: 73,
    fullName: "Joye",
    avatar: "https://robohash.org/nondoloremaccusamus.png?size=50x50&set=set1",
    university: 'Universidad Tecnológica del Choco "Diego Luis Cordoba"',
    department: "Services",
  },
  {
    id: 74,
    fullName: "Ester",
    avatar: "https://robohash.org/illuminventoremagni.png?size=50x50&set=set1",
    university: "Bangladesh University",
    department: "Legal",
  },
  {
    id: 75,
    fullName: "Regina",
    avatar: "https://robohash.org/quosdictaexpedita.png?size=50x50&set=set1",
    university: "Yerevan State Medical University",
    department: "Sales",
  },
  {
    id: 76,
    fullName: "Daphna",
    avatar: "https://robohash.org/voluptasvelitrerum.png?size=50x50&set=set1",
    university: "Universidad Complutense de Madrid",
    department: "Engineering",
  },
  {
    id: 77,
    fullName: "Meade",
    avatar: "https://robohash.org/admaioresconsectetur.png?size=50x50&set=set1",
    university: "Niigata University of International and Information Studies",
    department: "Training",
  },
  {
    id: 78,
    fullName: "Daryle",
    avatar: "https://robohash.org/culpaquisdebitis.png?size=50x50&set=set1",
    university: "Grace College",
    department: "Accounting",
  },
  {
    id: 79,
    fullName: "Ann",
    avatar:
      "https://robohash.org/recusandaevoluptatedolorum.png?size=50x50&set=set1",
    university: "Midlands State University",
    department: "Services",
  },
  {
    id: 80,
    fullName: "Sibeal",
    avatar: "https://robohash.org/nihilomnisincidunt.png?size=50x50&set=set1",
    university: "British Institute in Paris, University of London",
    department: "Services",
  },
  {
    id: 81,
    fullName: "Beverly",
    avatar: "https://robohash.org/inventoreimpeditsit.png?size=50x50&set=set1",
    university: "Université Paris Nanterre (Paris X)",
    department: "Legal",
  },
  {
    id: 82,
    fullName: "Leland",
    avatar: "https://robohash.org/cumquemodiad.png?size=50x50&set=set1",
    university: "Ivanovo State University",
    department: "Accounting",
  },
  {
    id: 83,
    fullName: "Penny",
    avatar:
      "https://robohash.org/velitdoloremveritatis.png?size=50x50&set=set1",
    university: "Zawiya Academy",
    department: "Services",
  },
  {
    id: 84,
    fullName: "Thain",
    avatar: "https://robohash.org/doloresitpossimus.png?size=50x50&set=set1",
    university: "Korea National Open University",
    department: "Training",
  },
  {
    id: 85,
    fullName: "Louella",
    avatar:
      "https://robohash.org/providentnecessitatibusrem.png?size=50x50&set=set1",
    university: "Massey University",
    department: "Services",
  },
  {
    id: 86,
    fullName: "Terri",
    avatar: "https://robohash.org/atautiure.png?size=50x50&set=set1",
    university: "Kansas State University",
    department: "Human Resources",
  },
  {
    id: 87,
    fullName: "Clerc",
    avatar: "https://robohash.org/autemeumquia.png?size=50x50&set=set1",
    university: "Universidad del Magdalena",
    department: "Human Resources",
  },
  {
    id: 88,
    fullName: "Evonne",
    avatar: "https://robohash.org/indoloribusautem.png?size=50x50&set=set1",
    university: "Universidad Nacional de Educación Enrique Guzmán y Valle",
    department: "Business Development",
  },
  {
    id: 89,
    fullName: "Johann",
    avatar: "https://robohash.org/veritatisnisiquos.png?size=50x50&set=set1",
    university: "Nanjing University of Aeronautics and Astronautics",
    department: "Engineering",
  },
  {
    id: 90,
    fullName: "Miles",
    avatar: "https://robohash.org/molestiaeestad.png?size=50x50&set=set1",
    university: "Bukkyo University",
    department: "Research and Development",
  },
  {
    id: 91,
    fullName: "Angeli",
    avatar:
      "https://robohash.org/laudantiumbeataerepudiandae.png?size=50x50&set=set1",
    university: "Université de Montpellier II",
    department: "Marketing",
  },
  {
    id: 92,
    fullName: "Aubrey",
    avatar: "https://robohash.org/quonatusat.png?size=50x50&set=set1",
    university: "Hochschule für Technik und Wirtschaft Dresden (FH)",
    department: "Product Management",
  },
  {
    id: 93,
    fullName: "Alayne",
    avatar:
      "https://robohash.org/veritatisdoloremquefacere.png?size=50x50&set=set1",
    university: "Northeast Forest University",
    department: "Research and Development",
  },
  {
    id: 94,
    fullName: "Adda",
    avatar: "https://robohash.org/nonconsequaturvel.png?size=50x50&set=set1",
    university: "University of Constanta Medical School",
    department: "Legal",
  },
  {
    id: 95,
    fullName: "Alard",
    avatar: "https://robohash.org/etrecusandaesapiente.png?size=50x50&set=set1",
    university: "Centre d'Etudes Supérieures des Techniques Industrielles",
    department: "Accounting",
  },
  {
    id: 96,
    fullName: "Deidre",
    avatar: "https://robohash.org/voluptatibusvelest.png?size=50x50&set=set1",
    university: "Kazan State Academy of Architecture and Civil Engineering",
    department: "Business Development",
  },
  {
    id: 97,
    fullName: "Judie",
    avatar:
      "https://robohash.org/possimusvoluptatemexercitationem.png?size=50x50&set=set1",
    university: "Nanjing University of Posts and Telecommunications",
    department: "Marketing",
  },
  {
    id: 98,
    fullName: "Alaine",
    avatar: "https://robohash.org/delectusutcorporis.png?size=50x50&set=set1",
    university: "University of Hull",
    department: "Research and Development",
  },
  {
    id: 99,
    fullName: "Nadiya",
    avatar: "https://robohash.org/nequemaximequia.png?size=50x50&set=set1",
    university: "Krirk University",
    department: "Sales",
  },
  {
    id: 100,
    fullName: "Maitilde",
    avatar:
      "https://robohash.org/laudantiumvoluptasfugit.png?size=50x50&set=set1",
    university: "Sungkyul University",
    department: "Engineering",
  },
  {
    id: 101,
    fullName: "Geri",
    avatar: "https://robohash.org/inciduntofficiiset.png?size=50x50&set=set1",
    university: "Nebraska Wesleyan University",
    department: "Product Management",
  },
  {
    id: 102,
    fullName: "Hermina",
    avatar:
      "https://robohash.org/inciduntexpeditatenetur.png?size=50x50&set=set1",
    university: "Utah Valley State College",
    department: "Engineering",
  },
  {
    id: 103,
    fullName: "Heath",
    avatar: "https://robohash.org/sequimagnimollitia.png?size=50x50&set=set1",
    university: "Semey State University",
    department: "Product Management",
  },
  {
    id: 104,
    fullName: "Nerissa",
    avatar: "https://robohash.org/enimnonrerum.png?size=50x50&set=set1",
    university: "Institute of Teachers Education, Perlis",
    department: "Product Management",
  },
  {
    id: 105,
    fullName: "Bondie",
    avatar: "https://robohash.org/quiarerummolestiae.png?size=50x50&set=set1",
    university: "Tokyo Women's College of Physical Education",
    department: "Research and Development",
  },
  {
    id: 106,
    fullName: "Maitilde",
    avatar:
      "https://robohash.org/consecteturvoluptatumsed.png?size=50x50&set=set1",
    university: "British College of Osteopathic Medicine",
    department: "Support",
  },
  {
    id: 107,
    fullName: "Astrix",
    avatar:
      "https://robohash.org/praesentiumlaborereiciendis.png?size=50x50&set=set1",
    university: "Universidad Adventista de Bolivia",
    department: "Human Resources",
  },
  {
    id: 108,
    fullName: "Melinde",
    avatar: "https://robohash.org/quidemexnumquam.png?size=50x50&set=set1",
    university: "Universidad Autónoma del Noreste",
    department: "Marketing",
  },
  {
    id: 109,
    fullName: "Camala",
    avatar: "https://robohash.org/doloritaqueat.png?size=50x50&set=set1",
    university: "Syrian Virtual University",
    department: "Human Resources",
  },
  {
    id: 110,
    fullName: "Donni",
    avatar: "https://robohash.org/undeomnispossimus.png?size=50x50&set=set1",
    university: "Perm State University",
    department: "Sales",
  },
  {
    id: 111,
    fullName: "Erena",
    avatar: "https://robohash.org/quiquibusdamipsam.png?size=50x50&set=set1",
    university: "Northern State Medical University",
    department: "Human Resources",
  },
  {
    id: 112,
    fullName: "Jobyna",
    avatar:
      "https://robohash.org/voluptatemvoluptatemminima.png?size=50x50&set=set1",
    university: "University of Gastronomic Sciences",
    department: "Research and Development",
  },
  {
    id: 113,
    fullName: "Nevins",
    avatar: "https://robohash.org/saepenesciuntet.png?size=50x50&set=set1",
    university: "American Graduate School in Paris",
    department: "Support",
  },
  {
    id: 114,
    fullName: "Tamarra",
    avatar: "https://robohash.org/autnostrumillum.png?size=50x50&set=set1",
    university: "Universidad Santa Paula",
    department: "Product Management",
  },
  {
    id: 115,
    fullName: "Elihu",
    avatar: "https://robohash.org/faceredoloresqui.png?size=50x50&set=set1",
    university: "International University of Africa (IUA)",
    department: "Services",
  },
  {
    id: 116,
    fullName: "Jeniffer",
    avatar: "https://robohash.org/inciduntdoloremea.png?size=50x50&set=set1",
    university: "Evergreen State College",
    department: "Legal",
  },
  {
    id: 117,
    fullName: "Darius",
    avatar: "https://robohash.org/doloresautvoluptas.png?size=50x50&set=set1",
    university: "Seikei University",
    department: "Support",
  },
  {
    id: 118,
    fullName: "Tedd",
    avatar: "https://robohash.org/cumadcorporis.png?size=50x50&set=set1",
    university: "Shimane University",
    department: "Training",
  },
  {
    id: 119,
    fullName: "Patti",
    avatar: "https://robohash.org/liberoeligendiullam.png?size=50x50&set=set1",
    university: "University of Maryland University College",
    department: "Training",
  },
  {
    id: 120,
    fullName: "Tabby",
    avatar: "https://robohash.org/suntessenulla.png?size=50x50&set=set1",
    university: "New Mexico Institute of Mining and Technology",
    department: "Services",
  },
  {
    id: 121,
    fullName: "Sissie",
    avatar: "https://robohash.org/debitislaboresaepe.png?size=50x50&set=set1",
    university: "Sungshin Women's University",
    department: "Marketing",
  },
  {
    id: 122,
    fullName: "Marybelle",
    avatar: "https://robohash.org/enimomnisautem.png?size=50x50&set=set1",
    university: "Missouri University of Science and Technology",
    department: "Training",
  },
  {
    id: 123,
    fullName: "Gray",
    avatar:
      "https://robohash.org/laudantiumofficiissuscipit.png?size=50x50&set=set1",
    university: "Textile Institute of Pakistan",
    department: "Legal",
  },
  {
    id: 124,
    fullName: "Emilio",
    avatar: "https://robohash.org/doloremautid.png?size=50x50&set=set1",
    university: "Kisii University",
    department: "Research and Development",
  },
  {
    id: 125,
    fullName: "Vinita",
    avatar: "https://robohash.org/doloresblanditiiset.png?size=50x50&set=set1",
    university: "Tay Nguyen University",
    department: "Training",
  },
  {
    id: 126,
    fullName: "Drucie",
    avatar:
      "https://robohash.org/exercitationemeosillo.png?size=50x50&set=set1",
    university: "Pyramid Education Center",
    department: "Legal",
  },
  {
    id: 127,
    fullName: "Reggy",
    avatar: "https://robohash.org/possimusillumeaque.png?size=50x50&set=set1",
    university: "Sistan & Balouchestan University",
    department: "Marketing",
  },
  {
    id: 128,
    fullName: "Sayre",
    avatar: "https://robohash.org/quianamquae.png?size=50x50&set=set1",
    university: "Kashan University",
    department: "Engineering",
  },
  {
    id: 129,
    fullName: "Egbert",
    avatar: "https://robohash.org/quodomnisnisi.png?size=50x50&set=set1",
    university: "Webster University, Vienna",
    department: "Legal",
  },
  {
    id: 130,
    fullName: "Joellen",
    avatar: "https://robohash.org/quidemautemcommodi.png?size=50x50&set=set1",
    university: "Universidade Federal do Paraná",
    department: "Sales",
  },
  {
    id: 131,
    fullName: "Justen",
    avatar:
      "https://robohash.org/voluptasdoloremtempore.png?size=50x50&set=set1",
    university: "Wesley University of Science and Technology",
    department: "Research and Development",
  },
  {
    id: 132,
    fullName: "Rosa",
    avatar: "https://robohash.org/utodioveniam.png?size=50x50&set=set1",
    university: "Phillips Graduate Institute",
    department: "Marketing",
  },
  {
    id: 133,
    fullName: "Coriss",
    avatar: "https://robohash.org/quiexplicaboet.png?size=50x50&set=set1",
    university: "Islamic Azad University, Roodehen",
    department: "Human Resources",
  },
  {
    id: 134,
    fullName: "Danila",
    avatar: "https://robohash.org/quiquiasunt.png?size=50x50&set=set1",
    university: "Minsk Institute of Management",
    department: "Business Development",
  },
  {
    id: 135,
    fullName: "Seline",
    avatar: "https://robohash.org/teneturtotamet.png?size=50x50&set=set1",
    university: "Escuela Politécnica del Ejercito",
    department: "Services",
  },
  {
    id: 136,
    fullName: "Emmalee",
    avatar: "https://robohash.org/adasperioresqui.png?size=50x50&set=set1",
    university: "University of the Netherlands Antilles, Curacao",
    department: "Business Development",
  },
  {
    id: 137,
    fullName: "Birgit",
    avatar: "https://robohash.org/esseeanobis.png?size=50x50&set=set1",
    university: "Prague International University",
    department: "Engineering",
  },
  {
    id: 138,
    fullName: "Janek",
    avatar: "https://robohash.org/magnamquisquameaque.png?size=50x50&set=set1",
    university: "New World University",
    department: "Legal",
  },
  {
    id: 139,
    fullName: "Germaine",
    avatar: "https://robohash.org/etconsequunturodit.png?size=50x50&set=set1",
    university: "National University",
    department: "Human Resources",
  },
  {
    id: 140,
    fullName: "Rutger",
    avatar: "https://robohash.org/quameligendimagni.png?size=50x50&set=set1",
    university: "Universidad Andina Simón Bolivar",
    department: "Sales",
  },
  {
    id: 141,
    fullName: "Aundrea",
    avatar: "https://robohash.org/autemnemofuga.png?size=50x50&set=set1",
    university: "American University of Afghanistan",
    department: "Legal",
  },
  {
    id: 142,
    fullName: "Tessie",
    avatar: "https://robohash.org/eosnemoet.png?size=50x50&set=set1",
    university: "Inha University",
    department: "Support",
  },
  {
    id: 143,
    fullName: "Adriano",
    avatar:
      "https://robohash.org/assumendaperferendisin.png?size=50x50&set=set1",
    university: "Yuan Ze University",
    department: "Business Development",
  },
  {
    id: 144,
    fullName: "Gerhard",
    avatar: "https://robohash.org/eosenimvoluptate.png?size=50x50&set=set1",
    university: "Nawroz University",
    department: "Accounting",
  },
  {
    id: 145,
    fullName: "Urbain",
    avatar: "https://robohash.org/quoetanimi.png?size=50x50&set=set1",
    university: "Niigata College of Pharmacy",
    department: "Legal",
  },
  {
    id: 146,
    fullName: "Cathyleen",
    avatar: "https://robohash.org/ipsumetqui.png?size=50x50&set=set1",
    university: "Soka University",
    department: "Legal",
  },
  {
    id: 147,
    fullName: "Esma",
    avatar: "https://robohash.org/undemodiet.png?size=50x50&set=set1",
    university: "Vitebsk State Academy of Veterinary Medicine",
    department: "Human Resources",
  },
  {
    id: 148,
    fullName: "Arne",
    avatar: "https://robohash.org/sintundeexpedita.png?size=50x50&set=set1",
    university: "Jewish University in Moscow",
    department: "Training",
  },
  {
    id: 149,
    fullName: "Isobel",
    avatar: "https://robohash.org/quisutnihil.png?size=50x50&set=set1",
    university: "Seoul Teological University",
    department: "Legal",
  },
  {
    id: 150,
    fullName: "Carlene",
    avatar: "https://robohash.org/etlaudantiumut.png?size=50x50&set=set1",
    university: "University of North Carolina at Greensboro",
    department: "Accounting",
  },
  {
    id: 151,
    fullName: "Wilbert",
    avatar:
      "https://robohash.org/perspiciatisdoloresratione.png?size=50x50&set=set1",
    university: "Nanjing University of Science and Technology",
    department: "Research and Development",
  },
  {
    id: 152,
    fullName: "Calvin",
    avatar: "https://robohash.org/accusamusatquelabore.png?size=50x50&set=set1",
    university: "College of Management",
    department: "Sales",
  },
  {
    id: 153,
    fullName: "Shana",
    avatar:
      "https://robohash.org/exercitationemnonminima.png?size=50x50&set=set1",
    university: "October 6 university",
    department: "Research and Development",
  },
  {
    id: 154,
    fullName: "Jerri",
    avatar:
      "https://robohash.org/maioressimiliqueinventore.png?size=50x50&set=set1",
    university: "Aktau State University",
    department: "Accounting",
  },
  {
    id: 155,
    fullName: "Gerhardine",
    avatar: "https://robohash.org/itaqueiustoet.png?size=50x50&set=set1",
    university: "Technical University of Radom",
    department: "Marketing",
  },
  {
    id: 156,
    fullName: "Camilla",
    avatar: "https://robohash.org/quodolorad.png?size=50x50&set=set1",
    university: "Gustavus Adolphus College",
    department: "Human Resources",
  },
  {
    id: 157,
    fullName: "Marcela",
    avatar: "https://robohash.org/dolorumaspernaturet.png?size=50x50&set=set1",
    university: "Instituto Tecnológico de Sonora",
    department: "Legal",
  },
  {
    id: 158,
    fullName: "Peyton",
    avatar:
      "https://robohash.org/voluptatemvoluptasnumquam.png?size=50x50&set=set1",
    university: "St.Patrick's International College, London",
    department: "Research and Development",
  },
  {
    id: 159,
    fullName: "Kenny",
    avatar: "https://robohash.org/maioresquaeratsaepe.png?size=50x50&set=set1",
    university: "Université de Montpellier I",
    department: "Services",
  },
  {
    id: 160,
    fullName: "Rozamond",
    avatar: "https://robohash.org/quobeataemolestiae.png?size=50x50&set=set1",
    university: "University of New York in Prague",
    department: "Legal",
  },
  {
    id: 161,
    fullName: "Carl",
    avatar:
      "https://robohash.org/expeditamolestiaeinventore.png?size=50x50&set=set1",
    university: "Agricultural University of Szczecin",
    department: "Product Management",
  },
  {
    id: 162,
    fullName: "Kristo",
    avatar: "https://robohash.org/quositaqueipsa.png?size=50x50&set=set1",
    university: "Miyagi University",
    department: "Product Management",
  },
  {
    id: 163,
    fullName: "Dulcinea",
    avatar: "https://robohash.org/insolutaexcepturi.png?size=50x50&set=set1",
    university: "Université de Lubumbashi",
    department: "Support",
  },
  {
    id: 164,
    fullName: "Erda",
    avatar:
      "https://robohash.org/doloremquevoluptasquaerat.png?size=50x50&set=set1",
    university: "Manipal University",
    department: "Marketing",
  },
  {
    id: 165,
    fullName: "Wallie",
    avatar: "https://robohash.org/teneturquoquis.png?size=50x50&set=set1",
    university: "Volgograd State Pedagogical University",
    department: "Support",
  },
  {
    id: 166,
    fullName: "Latia",
    avatar: "https://robohash.org/pariaturnumquamunde.png?size=50x50&set=set1",
    university: "Aga Khan University",
    department: "Accounting",
  },
  {
    id: 167,
    fullName: "Ferne",
    avatar: "https://robohash.org/quiutqui.png?size=50x50&set=set1",
    university: "Rogers State University",
    department: "Research and Development",
  },
  {
    id: 168,
    fullName: "Bridie",
    avatar:
      "https://robohash.org/doloribusvoluptatemerror.png?size=50x50&set=set1",
    university: "Ningbo University of Technology",
    department: "Legal",
  },
  {
    id: 169,
    fullName: "Stanfield",
    avatar:
      "https://robohash.org/autreiciendismolestiae.png?size=50x50&set=set1",
    university: "Universidad de la Integración de las Americas (UNIDAD)",
    department: "Product Management",
  },
  {
    id: 170,
    fullName: "Quintana",
    avatar: "https://robohash.org/nequefacereut.png?size=50x50&set=set1",
    university: "Otterbein College",
    department: "Services",
  },
  {
    id: 171,
    fullName: "Hubey",
    avatar: "https://robohash.org/quiquisitaque.png?size=50x50&set=set1",
    university: "Ecole Nationale Supérieure des Mines de Paris",
    department: "Sales",
  },
  {
    id: 172,
    fullName: "Faun",
    avatar:
      "https://robohash.org/inventoreminuscorrupti.png?size=50x50&set=set1",
    university: "University of the West Indies, Mona",
    department: "Research and Development",
  },
  {
    id: 173,
    fullName: "Lilla",
    avatar: "https://robohash.org/inrecusandaeut.png?size=50x50&set=set1",
    university: "Kansai Medical University",
    department: "Human Resources",
  },
  {
    id: 174,
    fullName: "Ewell",
    avatar: "https://robohash.org/ducimusquodsit.png?size=50x50&set=set1",
    university: "Tibet Agricultural and Animal Husbandry College",
    department: "Business Development",
  },
  {
    id: 175,
    fullName: "Nicholle",
    avatar: "https://robohash.org/omnisdoloremodi.png?size=50x50&set=set1",
    university: "Universidad del Salvador",
    department: "Sales",
  },
  {
    id: 176,
    fullName: "Ashlee",
    avatar:
      "https://robohash.org/voluptatumcumquevoluptatem.png?size=50x50&set=set1",
    university: "Dankook University",
    department: "Support",
  },
  {
    id: 177,
    fullName: "Si",
    avatar: "https://robohash.org/facilisrerumvitae.png?size=50x50&set=set1",
    university: "Paichai University",
    department: "Accounting",
  },
  {
    id: 178,
    fullName: "Brannon",
    avatar: "https://robohash.org/perspiciatisundeaut.png?size=50x50&set=set1",
    university: "Université Denis Diderot (Paris VII)",
    department: "Business Development",
  },
  {
    id: 179,
    fullName: "Fanni",
    avatar:
      "https://robohash.org/minusveritatisquibusdam.png?size=50x50&set=set1",
    university: "Universidad Autónoma Tomás Frías",
    department: "Sales",
  },
  {
    id: 180,
    fullName: "Chance",
    avatar: "https://robohash.org/quiasedminima.png?size=50x50&set=set1",
    university: "Universidad de Concepción del Uruguay",
    department: "Business Development",
  },
  {
    id: 181,
    fullName: "Roseann",
    avatar: "https://robohash.org/oditabautem.png?size=50x50&set=set1",
    university: "Universidad NUR",
    department: "Engineering",
  },
  {
    id: 182,
    fullName: "Camilla",
    avatar: "https://robohash.org/estrerumet.png?size=50x50&set=set1",
    university: "Florida Southern College",
    department: "Legal",
  },
  {
    id: 183,
    fullName: "Genevieve",
    avatar: "https://robohash.org/nisirecusandaesaepe.png?size=50x50&set=set1",
    university: "Tay Nguyen University",
    department: "Marketing",
  },
  {
    id: 184,
    fullName: "Marshall",
    avatar:
      "https://robohash.org/eumconsequunturreiciendis.png?size=50x50&set=set1",
    university: "Ohio University - Southern",
    department: "Human Resources",
  },
  {
    id: 185,
    fullName: "Moria",
    avatar:
      "https://robohash.org/voluptasmagnamlaudantium.png?size=50x50&set=set1",
    university: "Universidad Autónoma Metropolitana - Azcapotzalco",
    department: "Sales",
  },
  {
    id: 186,
    fullName: "Nelle",
    avatar:
      "https://robohash.org/consequaturducimuspossimus.png?size=50x50&set=set1",
    university: "University of Warwick",
    department: "Accounting",
  },
  {
    id: 187,
    fullName: "Clay",
    avatar: "https://robohash.org/dolorumvelitet.png?size=50x50&set=set1",
    university: "Carlow College",
    department: "Business Development",
  },
  {
    id: 188,
    fullName: "Jennie",
    avatar: "https://robohash.org/fugaplaceatest.png?size=50x50&set=set1",
    university: "Kermanshah University of Technology",
    department: "Legal",
  },
  {
    id: 189,
    fullName: "Reeta",
    avatar: "https://robohash.org/quifugiatnatus.png?size=50x50&set=set1",
    university: "Florida Metropolitan University, Tampa College",
    department: "Sales",
  },
  {
    id: 190,
    fullName: "Jourdan",
    avatar:
      "https://robohash.org/laborumconsequaturaut.png?size=50x50&set=set1",
    university: "Alahgaff University",
    department: "Services",
  },
  {
    id: 191,
    fullName: "Joscelin",
    avatar: "https://robohash.org/repellatplaceatest.png?size=50x50&set=set1",
    university: "Gulf University for Science and Technology",
    department: "Product Management",
  },
  {
    id: 192,
    fullName: "Sim",
    avatar: "https://robohash.org/etfugaut.png?size=50x50&set=set1",
    university: "University of Cyprus",
    department: "Engineering",
  },
  {
    id: 193,
    fullName: "Arley",
    avatar:
      "https://robohash.org/placeatvoluptatemmaxime.png?size=50x50&set=set1",
    university: "University of Hawaii - West Oahu",
    department: "Accounting",
  },
  {
    id: 194,
    fullName: "Sigfried",
    avatar: "https://robohash.org/dolorbeataecumque.png?size=50x50&set=set1",
    university: "Birla Institute of Technology, Ranchi",
    department: "Human Resources",
  },
  {
    id: 195,
    fullName: "Meggi",
    avatar: "https://robohash.org/autemcorporiserror.png?size=50x50&set=set1",
    university: "Fukuyama Heisei University",
    department: "Product Management",
  },
  {
    id: 196,
    fullName: "Stanleigh",
    avatar: "https://robohash.org/autquisest.png?size=50x50&set=set1",
    university: "Qafqaz University",
    department: "Engineering",
  },
  {
    id: 197,
    fullName: "Perren",
    avatar: "https://robohash.org/voluptatemiurenemo.png?size=50x50&set=set1",
    university: "Tashkent Medical Academy",
    department: "Product Management",
  },
  {
    id: 198,
    fullName: "Fair",
    avatar: "https://robohash.org/atquiavel.png?size=50x50&set=set1",
    university: "Institute of Social Studies",
    department: "Marketing",
  },
  {
    id: 199,
    fullName: "Haslett",
    avatar: "https://robohash.org/dictautsaepe.png?size=50x50&set=set1",
    university: "Aleksander Zelwerowicz State Theatre Academy",
    department: "Human Resources",
  },
  {
    id: 200,
    fullName: "Orelee",
    avatar: "https://robohash.org/porroutin.png?size=50x50&set=set1",
    university: "Tokiwa University",
    department: "Marketing",
  },
];

data.forEach(({ avatar, department, fullName, university }) => {
  const cardList = document.querySelector(".cardList").insertAdjacentHTML(
    "beforeend",
    `
      <div class="card">
        <div class ="left">
          <div class="imageBox">
            <img src="${avatar}" alt="">
          </div>
        </div>
        <div class="right">
            <div class="name">${fullName}</div>
            <div class="info">
              <div class="university">${university}</div>
                <div class="department">${department}</div>
            </div>
        </div>
      </div>
    `
  );
});
